   version: '3.8'

   services:
     db:
       image: postgres:17
       restart: always
       environment:
         POSTGRES_DB: postgres
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
       volumes:
         - db_data:/var/lib/postgresql/data/
         - ./data/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
       ports:
         - "5434:5432"

     web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
         - .:/app
       ports:
         - "8000:8000"
       depends_on:
         - db

     nginx:
       image: nginx:latest
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./static:/static
         - ./media:/media
       ports:
         - "80:80"
       depends_on:
         - web

   volumes:
     db_data:
